In [1]:
import pandas as pd
import quandl # need pip install <>
import math
import numpy as np
from sklearn import preprocessing,model_selection,linear_model,svm
# Need internet connection for sklearn
# svm - support vector model
# skelearn - http://scikit-learn.org/stable/index.html
# Approach followed is Supervised learning
# Idea here is to train a classifier. For that a 2D array X for the input variables and a 1D array y for the target variables. 
#The array X holds the features as columns and samples as rows . 
#The array y contains integer values to encode the class membership of each sample in X.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
#https://www.quandl.com/data/WIKI-Wiki-EOD-Stock-Prices - for getting data sets
# API Key - hWWAPym1jgJeSUKyGMLd
# user-abhinay.pass-wifeyy

In [3]:
#quandl.ApiConfig.api_key = 'hWWAPym1jgJeSUKyGMLd' - will import data only once so as not to hit limit

In [4]:
#data = quandl.get_table('WIKI/PRICES') -- will import data only once so as not to hit limit

In [5]:
#data

In [6]:
#data.to_csv("F:/BigData/inputfiles/ML/internet/google_stock_price.csv",sep=",")

In [7]:
data=pd.read_csv("F:/BigData/inputfiles/ML/internet/google_stock_price.csv",index_col='date')


In [8]:
# open	high	low	close	volume	ex-dividend	split_ratio	adj_open	adj_high	adj_low	adj_close	adj_volume
# above attributes are features
# In machine learning you can have as much feature you want and have meaningful feature
# Need meaningful data for arrive at pattern or find a pattern
# adj - adjusted price here shows the stock split
# find relationship between features or column label e.g. low price of stocks might bring in more buyer(increased volume)
# Pick the meaningful features and discard others

# Open price, high and low - tells us about the volatility of market share 

In [9]:
df=data[['adj_open','adj_high','adj_low','adj_close','adj_volume']]

In [10]:
# Find percentage change in price of stock
df['HL_PCT']=(data['adj_high'] - data['adj_low'])/data['adj_low'] * 100

e:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [11]:
#Daily percentage change
df['PCT_change']=(data['adj_close'] - data['adj_open'])/data['adj_open'] * 100
#df

e:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [12]:
# Now take the columns which are of intrest to us
df = df [['adj_close','HL_PCT','PCT_change','adj_volume']]
#df

In [13]:
# Target here is to predict future - and that is gone be price of stock and this price is label for us
# Idea here is to get the adjusted close price for the day
#


In [14]:
#df['adj_close']

In [15]:

#df['adj_close'].shift


In [16]:

# Introduce a new column, this is going to be our label?
forecast_col = 'adj_close' #forecast_col this is just a variable at this point of time

df.fillna(-99999,inplace=True) # ML cannot work with NaN data so need to replace it with some outlier value
                               # in real there are lots of missing data. One column might have a missing data while 
                               # others may have data, so not a good idea to ignore a row as one of columns had NaN

forecast_out=int(math.ceil(0.01*len(df))) 
                                    # math.ceil, rounded off to nearest integer e.g. math.ceil(0.3) gives 1
                                    # len(df) - gives the no. of rows in df
                                    # 0.1 - represents 10% of dataframe - 10/100
                                    # 0.01 - represents 1% of dataframe - 1/100                                                                 
                                    # Give that there are 10000 rows forecast_out would be set to 100


df['label']=df[forecast_col].shift(-forecast_out) 
# label column is copying values from forecast_col
# shift is moving the column values by 100 posistion, so value in column label in row is now 100 days head of date
# How shift operation works(shifting on z)
# 
#  original df      after shift(1) - down      after shift(-1) - up
#  x   y    z       x     y     z                   x      y      z
#  1   206  214     1   206  Nan                   1      206    234      
#  2   226  234     2   226  214                   2      226    253 
#  3   245  253     3   245  234                   3      245    291
#  4   283  291     4   283  253                   4      283    NaN
#

# define X and y, both as array
# feature are X 
# labels are y
X=np.array(df.drop(['label'],1)) # drop labels colums and assign all other feature to X
print(X)
X.shape()
X=preprocessing.scale(X) # X is nd array of 4 columns and 9900 rows
print('After preprocessing scale')
print(X)
X.shape()
#preprocessing.scale - Standardize a dataset along any axis
X=X[:-forecast_out] # 0th row to forecast_out th row
X_lately=X[-forecast_out:] #forecast_out th row to last row, this is row against which prediction would be 
                           # These are the rows in past
    


# X is 9900 rows and 4 columns

# Since forecast_out = 100 there would be 100 NaN, time to drop them now
df.dropna(inplace=True)
y=np.array(df['label']) # label column assigned as an array




# Now lets create the label 
#df['adj_close'] shows data as
#date
#1999-11-18    30.079673
#df['adj_close'].shift , it shifts the data up negatively. now data shows up like
#
#1999-11-18    30.079673

# At the end of this we have got features and labels


[[  3.00796732e+01   2.50000000e+01  -3.29670330e+00   4.47399000e+07]
 [  2.76049364e+01   8.01306204e+00  -5.96180717e+00   1.08971000e+07]
 [  3.00796732e+01   9.83524713e+00   6.51174050e+00   4.70520000e+06]
 ..., 
 [  1.49951282e+00   2.32558140e+00  -1.09090909e+00   6.79002750e+05]
 [  1.55050728e+00   4.65116279e+00   3.40073529e+00   4.00275000e+03]
 [  1.51605156e+00   0.00000000e+00   0.00000000e+00   1.25502750e+05]]
After preprocessing scale
[[-0.21250145  4.53343684 -0.90470133  8.70719362]
 [-0.23016629  0.82505465 -1.61933183  1.52871114]
 [-0.21250145  1.22285199  1.72536995  0.21533146]
 ..., 
 [-0.4165085  -0.41656712 -0.31323176 -0.63867549]
 [-0.4161445   0.0911256   0.89117386 -0.78185146]
 [-0.41639045 -0.92425983 -0.02071149 -0.75607978]]


In [17]:
# Now time for classifier, train our machine
# sklearn library
#
#       - preprocessing
#       - cross_validation helps with stats, avoiding biased stats
#       - svm - support vector machine
#       - LinearRegression
print(X_lately)

[[-0.4166364  -0.41083587 -0.34110364 -0.75291989]
 [-0.41639045 -0.68347909  0.27503511 -0.76151045]
 [-0.41639045 -0.41656712 -0.02071149 -0.77067371]
 [-0.41639045 -0.41656712 -0.02071149 -0.7589433 ]
 [-0.41639045 -0.68347909 -0.02071149 -0.77811886]
 [-0.4165085  -0.41656712 -0.31323176 -0.76237953]
 [-0.41639045 -0.44269836  0.27503511 -0.75722519]
 [-0.41602645 -0.18995155  0.88122602 -0.71397603]
 [-0.41589855 -0.17824374  0.28587308 -0.75550708]
 [-0.41565261 -0.44967751  0.56220934 -0.77640075]
 [-0.41565261 -0.92425983 -0.02071149 -0.78155508]
 [-0.41602645 -0.92425983 -0.02071149 -0.77754616]
 [-0.41602645 -0.92425983 -0.02071149 -0.76838289]
 [-0.41589855 -0.43913124  0.28587308 -0.76208315]
 [-0.41639045 -0.42810559 -0.61658612 -0.77410993]
 [-0.4166364  -0.41656712 -0.63012873 -0.71283062]
 [-0.4166364  -0.92425983 -0.02071149 -0.78270049]
 [-0.41639045 -0.41656712  0.60287824 -0.78098238]
 [-0.41639045 -0.92425983 -0.02071149 -0.78270049]
 [-0.41639045 -0.41656712 -0.02

In [18]:
len(X) ,len(y) # length of X and y should match

(9900, 9900)

In [19]:
X_train,X_test,y_train,y_test = model_selection.train_test_split(X,y,test_size=0.2)
#Split arrays or matrices into random train and test subsets
#test_size shold be between 0.0 and 1.0 
#


In [20]:
# train and test have same no of rows for X and y
#X_train.shape - (7920, 4)
#X_test.shape - (1980, 4)
#y_train.shape - (7920,)
#y_test.shape - (1980,)

In [21]:
clf=linear_model.LinearRegression(n_jobs=-1) 
clf.fit(X_train,y_train) # fit is done on sample and in real world would be book taught in school
accuracy=clf.score(X_test,y_test) # test is done on probable outcome and in real world it maps to questions in exam
print(forecast_out,accuracy)

# Important fact is that Linearregresion can be multi threaded, meaning this job can be 
# run in batches, look at the help page and go for n_jobs -1 , means as many batch as possible
# Support vector cannot be run in multi threaded

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)

100 0.631676076832


In [22]:
#df.tail()
#X_lately
X

array([[-0.21250145,  4.53343684, -0.90470133,  8.70719362],
       [-0.23016629,  0.82505465, -1.61933183,  1.52871114],
       [-0.21250145,  1.22285199,  1.72536995,  0.21533146],
       ..., 
       [-0.41725618, -0.92425983, -0.02071149, -0.78270049],
       [-0.41750213, -0.09580946, -0.68312153, -0.75779789],
       [-0.41762019, -0.92425983, -0.02071149, -0.77926427]])

In [23]:
#clf=svm.SVR(kernel='poly') # changed algorithm to SVR, support vector regression algorithm
#clf.fit(X_train,y_train) # fit is done on sample and in real world would be book taught in school
#accuracy=clf.score(X_test,y_test) # test is done on probable outcome and in real world it maps to questions in exam
#print(forecast_out,accuracy)

In [24]:
df.describe()

adj_close       HL_PCT   PCT_change    adj_volume        label
count  9900.000000  9900.000000  9900.000000  9.900000e+03  9900.000000
mean     60.440041     4.250967     0.075989  3.726284e+06    59.896390
std     140.683106     4.594454     3.741021  4.724525e+06   140.790568
min       0.895849     0.000000   -30.428571  0.000000e+00     0.895849
25%      16.560000     1.837968    -1.253964  9.988500e+05    16.154152
50%      26.435931     3.030303     0.000000  2.514600e+06    26.078137
75%      41.538295     5.075710     1.281516  4.791037e+06    41.126178
max    1196.360000   106.349206   106.349206  1.377672e+08  1196.360000

In [25]:
#df[-forecast_out:]
X[:]

array([[-0.21250145,  4.53343684, -0.90470133,  8.70719362],
       [-0.23016629,  0.82505465, -1.61933183,  1.52871114],
       [-0.21250145,  1.22285199,  1.72536995,  0.21533146],
       ..., 
       [-0.41725618, -0.92425983, -0.02071149, -0.78270049],
       [-0.41750213, -0.09580946, -0.68312153, -0.75779789],
       [-0.41762019, -0.92425983, -0.02071149, -0.77926427]])

In [26]:
help(df.drop)

Help on method drop in module pandas.core.generic:

drop(labels, axis=0, level=None, inplace=False, errors='raise') method of pandas.core.frame.DataFrame instance
    Return new object with labels in requested axis removed.
    
    Parameters
    ----------
    labels : single label or list-like
    axis : int or axis name
    level : int or level name, default None
        For MultiIndex
    inplace : bool, default False
        If True, do operation inplace and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and existing labels are dropped.
    
        .. versionadded:: 0.16.1
    
    Returns
    -------
    dropped : type of caller

